apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
 - path: patch.yaml
   target:
     kind: ServiceAccount
     name: source-controller
     namespace: flux-system
     version: v1
  
